# another try!
# https://raw.githubusercontent.com/kofj/travis-golang/master/.travis.yml
language: go
go:
  - 1.7
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get -u github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/elazarl/go-bindata-assetfs/...
script:
  - golint .
  - go generate
  - go test ./...
before_deploy:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -ldflags="-w"

deploy:
  provider: releases
  file_glob: true
  api_key: $GITHUB_TOKEN
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
